language: node_js
node_js:
  - 13.5.0
cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  skip-cleanup: true
  api_key:
    secure: cce95f9a-ba4a-4e14-99d6-aa0c13e32887
  app: svisni
  on:
    branch: master
  
 


