language: node_js
node_js:
  - 13.5.0
cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  skip-cleanup: true
  api_key:
    secure: cce95f9a-ba4a-4e14-99d6-aa0c13e32887
  app: svisni
  on:
    branch: master
  

###
  # local_dir: public
  # keep-history: true
  # on:
  #   branch: master
  # before_script:
  #   - "npm i -g gatsby"
  #   - "npm i"
  # after_success:
  #   - "npm run deploy"


#     language: node_js
# node_js:
#   - 10.17.0
# cache: yarn

# install:
#  - npm install

# script:
# - npm run build

# deploy:
#   provider: heroku
#   api_key:
#     secure: "cce95f9a-ba4a-4e14-99d6-aa0c13e32887"
#   on:
#     all_branches: true
  
  # skip-cleanup: true
  # github-token: $GITHUB_TOKEN
  # on:
  #   branch: master
  # api_key:
  # secure: "cce95f9a-ba4a-4e14-99d6-aa0c13e32887"
  # app: svisni-sushi
  # run:
  # - restart

  # deploy:
  # provider: heroku
  # api_key:
  # secure: "cce95f9a-ba4a-4e14-99d6-aa0c13e32887"
  # app: svisni-sushi
  # run:
  # - restart

# deploy:
#   provider: heroku
#   edge: true
#   skip-cleanup: true
#   local_dir: public
#   keep-history: true
#   api_key:
#     secure: cce95f9a-ba4a-4e14-99d6-aa0c13e32887
#   app: svisni
#   on:
#     branch: master
#   before_script:
#     - "npm i -g gatsby"
#     - "npm i"
#   after_success:
#     - "npm run deploy"