# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: yarn test






# version: 2
# jobs:
#   build:
#     docker: 
#         - image: circleci/node10
#     steps:
#       - checkout
#       - run:
#           name: Run Build Command
#           command: gatsby build
    
#     deploy:
#        docker:
#           - image: circleci/node10
#         steps:
#           - checkout
#           - run:
#               name: Run Deploy Command
#               command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
   
# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - build
#       - deploy



























            # # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: yarn test



# version: 2
# jobs:
#   build:
#    docker:  # run the steps with Docker
#       - image: circleci/node:10.17.0

#     steps:
#       - checkout
#       - run: npm install
#       - run: npm test
#       - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
#       - run: npm run build
      
     
        
  # deploy:
  #   docker: # run the steps with Docker
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master




# version: 2
# jobs:
#   build:
#     docker: # run the steps with Docker
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - restore_cache:
#          keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#       - run:
#           name: update npm
#           command: 'sudo npm install -g npm@latest'
#       - run:
#           name: Install node modules
#           command: yarn install
#       - run:
#           name: Build
#           command: npm run build
#       - run:
#           name: Deploy
#           command: git push https://heroku:cce95f9a-ba4a-4e14-99d6-aa0c13e32887@git.heroku.com/svisni.git master
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - steps



















# version: 2
# jobs:
#   build:
#     docker: # run the steps with Docker
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Build
#           command: yarn run build
#       - run:
#           name: Deploy
#           command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
# # workflows:
# #   version: 2
# #   build_and_test:
# #     jobs:
# #       steps:
# #           - build
        









# version: 2
# jobs:
#   build:
#     docker: # run the steps with Docker
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - restore_cache:
#          keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#       - run:
#           name: update npm
#           command: 'sudo npm install -g npm@latest'
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Install node modules
#           command: yarn install
#       - run:
#           name: Build
#           command: npm run build
#       - run:
#           name: Deploy
#           command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - unit
#       - integration
#       - release:
#           requires:
#             - unit
#             - integration



version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:10.17.0
    steps:
      - checkout
      - run:
          name: install npm
          command: 'npm install -g npm@latest'
      - run:
          name: npm test
          command: npm test
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      - run:
          name: Build
          command: npm run build

# version: 2
# jobs:
#   build:
#    docker:  # run the steps with Docker

#       - image: circleci/node:10.17.0

#     steps:
#       - checkout
#       - run: 'npm install'
#       - run: npm test
#       - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
#       - run: npm run build